# Generated by Django 5.1.1 on 2024-10-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="category",
            field=models.CharField(default="General", max_length=255),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="title",
            field=models.CharField(default="Untitled", max_length=255),
        ),
    ]
