# Generated by Django 5.1.1 on 2024-10-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_bookmark_category_bookmark_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="category",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
