# Generated by Django 5.1.1 on 2024-10-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_bookmark_category_alter_bookmark_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="meta_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
